### PR TITLE
expect callables instead of closures for hydrators/transformers

### PR DESCRIPTION
**Pull request by dimvic**

### CODE REVIEW

**Comment by kocsismate** [comment]
Really nice work! I love the `callable[]` parts in the docblocks as they make the interfaces way more clear. I'll do the rest of the work (updating the changelog, readme etc.) to prepare a release.

**Comment by dimvic** [comment]
Thank you :)
I was about to suggest a release as 0.10.2 as well, so that I can configure my composer files to something other than dev-master again!

**Comment by kocsismate** [comment]
Unfortunately I had to remove the `call_user_func_array` calls, because they failed some tests when arguments were passed to the hydrator by reference. It came out that this function can't handle passing by reference, but I want to keep this feature.

So I had to bring back the original `$hydrator(...)` function calls. After playing with them, it turned out that they could almost invoke all the types of callables, except of this one: `"Class::staticFunction"` (however HHVM can do it!). Could you accept the fact that callables in this form can't be used as hydrators?

**Comment by dimvic** [comment]
It makes sense the way you put it, if you want to pass by reference just keep the closures, after all if you want to call a Class::staticFunction you can still do that by calling in inside the closure, it's not a big deal after all. I'm sorry for the time you had to waste on this!

**Comment by kocsismate** [comment]
It was not too much time! Anyway, I have to investigate why the broken tests were not indicated on this page before accepting the PR. And I try to find out why PHP can't invoke the `"Class::staticFunction"` type of `callables`.

**Pull request merged**
