### PR TITLE
PageBasedPaginationLinkProviderTrait: Fix getPrevLink, getNextLink and getLastPage

### LINKED ISSUE #48: PageBasedPaginationProviderTrait getPrevLink and getNextLink generate wrong links
Hi,

first thank you for the great library! I use it in my project with Zend Expressive and it helped me a lot to implement JSONAPI.

I use the PageBasedPaginationProviderTrait to generate pagination links and I found out it generates Prev and Next links wrong.

The Prev link is null on the last page and the Next link is null on the page before the last page.
The problem is [here](https://github.com/woohoolabs/yin/blob/master/src/JsonApi/Schema/Pagination/PageBasedPaginationLinkProviderTrait.php#L66) and [here](https://github.com/woohoolabs/yin/blob/master/src/JsonApi/Schema/Pagination/PageBasedPaginationLinkProviderTrait.php#L79).
I believe that `|| $this->getPage() >= $this->getLastPage()` should be removed from line 66 and `$this->getPage() + 1 >= $this->getLastPage()` should become `$this->getPage() >= $this->getLastPage()` on line 79.

Please let me know if this is correct and if I should make a PR to fix it. Thanks!

### PR DESCRIPTION
**Pull request by pdrosos**
Hi,

This PR fixes #48. I added two additional tests about it.
When I fixed the issues in #48 and ran the tests, getNextLinkWhenPageIsLast failed, so I have found another issue in getLastPage and fixed it, making it simpler to read.

Please let me know if you approve the changes and if I need to do something else.

### CODE REVIEW

**Comment by kocsismate** [comment]
That's really nice a PR! Thank you!

**Comment by pdrosos** [comment]
Glad it helped! Will there be a new release soon, or we should use the master branch?

**Comment by kocsismate** [comment]
The next release will be v1.0 and it should come really soon. I definitely want it to happen in the following 1-2weeks. I only want to add more tests and fix the found bugs.

So you can use the master branch for sure until then. But please be aware that there was a PHP version bump since 0.11 so Yin now needs PHP 5.6. I hope it doesn't affect you!

**Comment by pdrosos** [comment]
Thanks and nice to hear it! Will wait for 1.0.
PHP 5.6 is fine, many other libraries and frameworks require it too. I am currently using PHP 7 for new projects, so no problem about it :).

**Comment by kocsismate** [comment]
Release is done! 🎉

**Comment by pdrosos** [comment]
Thanks!

**Pull request merged**
