### PR TITLE
issue-64 - Fix conditions for triggering deserialization of parsed body

### PR DESCRIPTION
**Pull request by leclairmael**

### CODE REVIEW

**Comment by kocsismate** [comment]
Hey there :)

Thank you for the PR, but I have to ask some questions before merging it:
- Which HTTP library do you use? I am only familiar with Zend/Diactoros, but never faced this issue because `getParsedBody()` defaults to `null`.
- PSR-7 says the following about the `getParsedBody()` method:
>This method may return any results of deserializing the request body content; as parsing returns structured content, the potential types MUST be arrays or objects only. A null value indicates the absence of body content. (https://github.com/php-fig/http-message/blob/master/src/ServerRequestInterface.php#L161)

Although I am not sure, I think regarding an empty array result as if the body hasn't been parsed wouldn't follow the specification. What do you think? Can your problem be the fault of your HTTP library?

**Comment by leclairmael** [comment]
Hello @kocsismate,

Actually, I do use Diactoros as well. I usually call `ServerRequestFactory::fromGlobals()` to initialize my `ServerRequest`. Having looked at the code of `fromGlobals`, `$parsedBody` will contain `$_POST` by default, which is evaluated to an empty array when I send a JSON body.

Cheers

**Comment by kocsismate** [comment]
Wow, that's interesting! I could only avoid this problem because I don't use `ServerRequestFactory::fromGlobals()` so I'll accept the PR, thank you very much for bringing it up and implementing the fix!

I am going to release your path for both the 1.* and 2.* branches tonight. :)

**Comment by leclairmael** [comment]
Hello,
Just a quick note: 1.* branches are fine as you used `empty()` instead of `=== null` back then ;)
Cheers

**Pull request merged**
