### PR TITLE
include relationship name in relationship hydrator closure

### PR DESCRIPTION
**Pull request by dimvic**
In accordance to the earlier changes :) I know now that you are going to rework hydrators, but I am trying to use something like Factories in my project.
Also, should I suggest that instead of type hinting for closure you could type hint for callable? :)

### CODE REVIEW

**Comment by kocsismate** [comment]
The PR is good! :) And what would be the advantage of type hinting against callables? I am just curious, because I can surely change type hinting if it makes sense :)

**Comment by dimvic** [comment]
Well, changing it to callable (AND changing $function() calls to call_user_func_array($callable)) would allow for all types of callables to be passed in addition to lambda functions, which is not necessary of course, but could help in some cases, like if you want to use a Factory or a class with static methods for attribute transformers, hydrators etc and not have to call these inside a lambda. Ultimately it could allow for these kind of callables to be bundled in classes and inject them using DI (haven't thought much about it, it's a shallow thought).

It might as well be needless, I have not dealt with DDD so I don't know if/how that would fit your concepts, but asking for callables is generally more versatile than asking strictly anonymous functions. I also don't know performance-wise how the two compare...

If you are in for callables I can do it an submit a PR.

**Comment by dimvic** [comment]
Oh, this is what I've been working on using yin... It's yii 1.1 based so it's kind of useless for the vast majority, but oh well

https://github.com/dimvic/yii-yin
https://github.com/dimvic/yii-yin-example

**Comment by kocsismate** [comment]
Thank you for your explanation! I am in favor of type hinting against `callable`! Could you please create a PR? :)

By the way, the only reason I type type hinted against closures when I created the hydrator interface back then that I didn't think that someone would need general callables. It's interesting to hear otherwise :)

**Pull request merged**
