### PR TITLE
Fix typos and clarify language

### PR DESCRIPTION
**Pull request by chasingSublimity**
Fixed broken "Request/response" link and typos, clarified language and syntax.

### CODE REVIEW

**Comment by kocsismate** [comment]
Hey,

Sorry for the delay! I like the majority of your changes, I will comment those expressions which I don't find approrite.

However, you should resolve the conflicts first if you are still interested in finishing the PR. Otherwise please close this issue, and I will include your fixes manually (without merging).

**Comment by chasingSublimity** [comment]
No worries! I imagine hacktoberfest has kept you busy. :)

I'm happy to make edits based on your comments. To be honest, regarding resolving conflicts, I'm not exactly sure what that process looks like. I am a writer currently training to be a developer, so I don't quite have all the knowledge I need yet. 

If you can briefly explain how to locate and resolve these merges, I'll hop on it.

Thanks!

**Comment by kocsismate** [comment]
Ah, no, unfortunately it wasn't Hacktoberfest :D I just worked a lot on other side-projects of mine.

I can help you for sure! You have to merge the master branch of woohoolabs/yin to your own branch. Here is a short description along which you can start: https://github.com/genome/docs/wiki/How-do-I-fix-my-pull-request-if-it-cannot-be-automatically-merged%3F I don't know if there is a good GUI for this task (the desktop Github app can't do this), so you probably have to use the command line.

As soon as you are ready with this, you can start resolving the conflicts. Here is a detailed explanation about it: https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/ Now there are GUI alternatives that can help you do this (PHPStorm itself can also help: https://www.jetbrains.com/help/phpstorm/2016.2/resolving-conflicts.html), but smaller conflicts can be resolved without any visual help.

Furthermore, there is also another alternative which is the easiest to do: you can destroy your fork, refork woohoolabs/yin and redo all the fixes which are still valid (some of them have already been fixed by another PRs).

Good luck with this, I hope you'll find my description useful!

**Comment by chasingSublimity** [comment]
I'll submit another PR. Thanks!

**Pull request closed without merging**
